# %% [markdown]
# # SatQuery AI - CDVQA Change Analysis Fine-Tuning (Colab T4 GPU)
# Run this notebook sequentially in Google Colab with a T4 GPU.
# This script CONTINUES fine-tuning from the existing `satquery_vqa_adapter` 
# using the CDVQA formatted dataset (from `prep_cdvqa.py`).

# %% [markdown]
# ### 1. Setup & Installation
# Install the necessary libraries for 4-bit quantization, PEFT, and fine-tuning.

# %%
!pip install -q -U torch transformers peft trl bitsandbytes accelerate datasets huggingface_hub

# %% [markdown]
# ### 2. Data Preparation
# Load the pre-formatted CDVQA dataset generated by `prep_cdvqa.py`.
# Make sure the `cdvqa_formatted` folder is uploaded/available in the Colab environment.

# %%
import os
import json
from datasets import Dataset
from PIL import Image

print("Loading formatted CDVQA dataset...")

train_data = []
with open("cdvqa_formatted/train.jsonl", "r") as f:
    for line in f:
        train_data.append(json.loads(line))
        
eval_data = []
with open("cdvqa_formatted/eval.jsonl", "r") as f:
    for line in f:
        eval_data.append(json.loads(line))

# Convert paths to absolute for the dataset
for item in train_data:
    item['image'] = os.path.join("cdvqa_formatted", item['image'])
for item in eval_data:
    item['image'] = os.path.join("cdvqa_formatted", item['image'])

hf_dataset = Dataset.from_list(train_data)
print(f"Prepared {len(hf_dataset)} training samples and {len(eval_data)} evaluation samples.")

# %% [markdown]
# ### 3. Load Base Model and Existing LoRA Adapter
# We load PaliGemma 3B in 4-bit, then load the EXISTING `satquery_vqa_adapter` 
# and make it trainable to continue fine-tuning.

# %%
import torch
from transformers import AutoProcessor, PaliGemmaForConditionalGeneration, BitsAndBytesConfig
from peft import PeftModel

model_id = "google/paligemma-3b-pt-224"
adapter_path = "./satquery_vqa_adapter" # Ensure this folder is uploaded/available

# 4-bit quantization config (same as before)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

print("Loading processor...")
processor = AutoProcessor.from_pretrained(model_id)

print("Loading base model in 4-bit...")
base_model = PaliGemmaForConditionalGeneration.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map={"": 0}
)

# Freeze vision encoder and multi-modal projector
for param in base_model.vision_tower.parameters():
    param.requires_grad = False
for param in base_model.multi_modal_projector.parameters():
    param.requires_grad = False

print(f"Loading existing LoRA adapter from {adapter_path} and setting is_trainable=True...")
model = PeftModel.from_pretrained(base_model, adapter_path, is_trainable=True)
model.print_trainable_parameters()

# %% [markdown]
# ### 4. Training Loop
# We use a custom collator to format the data for PaliGemma.

# %%
from transformers import TrainingArguments, Trainer

def collate_fn(examples):
    texts = [ex['prefix'] for ex in examples]
    labels = [ex['suffix'] for ex in examples]
    images = [Image.open(ex['image']).convert("RGB") for ex in examples]
    
    inputs = processor(
        text=texts,
        images=images,
        suffix=labels,
        return_tensors="pt",
        padding="longest",
    )
    
    return {
        "input_ids": inputs["input_ids"],
        "attention_mask": inputs["attention_mask"],
        "pixel_values": inputs["pixel_values"],
        "labels": inputs["labels"],
    }

training_args = TrainingArguments(
    output_dir="./paligemma_change_adapter",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=2,
    learning_rate=2e-4,
    bf16=False,
    fp16=True,
    logging_steps=10,
    save_strategy="no",
    optim="paged_adamw_8bit",
    remove_unused_columns=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=hf_dataset,
    data_collator=collate_fn,
)

print("Starting training...")
trainer.train()

print("Saving NEW LoRA adapter...")
new_adapter_path = "./satquery_change_adapter"
model.save_pretrained(new_adapter_path)
processor.save_pretrained(new_adapter_path)
print(f"Saved to {new_adapter_path}!")

# %% [markdown]
# ### 5. Held-Out Sanity Check (Eval)
# Let's test the newly fine-tuned model on the 10 CDVQA holdout samples.

# %%
model.eval()

print("=== SANITY CHECK EVALUATION ===")
for ex in eval_data:
    img = Image.open(ex['image']).convert("RGB")
    prompt = ex['prefix']
    
    inputs = processor(text=prompt, images=img, return_tensors="pt")
    inputs = {k: v.to(model.device) for k, v in inputs.items()}
    
    with torch.no_grad():
        output = model.generate(**inputs, max_new_tokens=50)
    
    prompt_len = inputs["input_ids"].shape[1]
    predicted = processor.decode(output[0][prompt_len:], skip_special_tokens=True)
    
    print(f"Q: {ex['prefix']}")
    print(f"Truth: {ex['suffix']}")
    print(f"Pred : {predicted}")
    print("-" * 40)

# %% [markdown]
# ### 6. Download Adapter Weights
# Run this cell to zip the new change detection adapter and download it.

# %%
import shutil
from google.colab import files

print("Zipping new adapter...")
shutil.make_archive("satquery_change_adapter", 'zip', "./satquery_change_adapter")
print("Downloading...")
files.download("satquery_change_adapter.zip")
